---
RecipeFormatVersion: '2020-01-25'
ComponentName: com.example.ros2.demo
ComponentVersion: '1.0.0'
ComponentDescription: 'A basic component that runs a simple pub/sub ROS2 application'
ComponentPublisher: Amazon
ComponentDependencies:
  aws.greengrass.DockerApplicationManager:
    VersionRequirement: ~2.0.0
  aws.greengrass.TokenExchangeService:
    VersionRequirement: ~2.0.0
ComponentConfiguration:
  DefaultConfiguration:
    accessControl:
      aws.greengrass.ipc.mqttproxy:
        com.example.PubSubPublisher:pubsub:1:
          policyDescription: "Allows access to publish and subscribe to MQTT topics."
          operations:
          - "aws.greengrass#PublishToIoTCore"
          - "aws.greengrass#SubscribeToIoTCore"
          resources:
          - "chatter"
          - "cloud_chatter"
Manifests:
  - Platform:
      os: all
    Lifecycle:
        Run: |
           docker-compose -f {artifacts:path}/docker-compose.yaml up
    Artifacts:
      - URI: "docker:<YOUR_PRIVATE_ECR_IMAGE_ID_ROS_GREENGRASS_DEMO>"
      - URI: "s3://<YOUR_BUCKET_NAME>/com.example.ros2.demo/1.0.0/artifacts/docker-compose.yaml"
